// Generated by CoffeeScript 1.10.0
var fn;

module.exports = fn = function(buffer) {
  var code, i, j, len, mask, mode, n;
  mode = 0;
  for (i = j = 0, len = buffer.length; j < len; i = ++j) {
    n = buffer[i];
    if (mode) {
      if (0x80 !== (0xC0 & n)) {
        return;
      }
      code = code << 6 | n & 0x3F;
      if (--mode) {
        continue;
      }
      if (fn.maxBytes < 5 && code > 0x0010FFFF) {
        return;
      }
      if (!fn.surrogates && (0xD800 <= code && code <= 0xDFFF)) {
        return;
      }
      if (!(code >> mask)) {
        return;
      }
      continue;
    }
    if (!(n & 0x80)) {
      continue;
    }
    if (n === 0xFF || n === 0xFE || n === 0xC0 || n === 0xC1) {
      return;
    }
    if (!(n & 0x40)) {
      return;
    }
    mode = 1;
    mask = 0x20;
    while (n & mask) {
      mask >>= 1;
      mode++;
    }
    if (mode >= fn.maxBytes) {
      return;
    }
    code = n & mask - 1;
    mask = 5 * mode + 1;
  }
  if (mode) {
    return;
  }
  return true;
};

fn.isValidUTF8 = fn;

fn.maxBytes = 4;

fn.surrogates = false;
